version: '3.8'

services:
  client:
    build: ./client
    image: my-client-image
    ports:
      - "3000:3000"  # Host:Container (you can change to 4000:3000 if desired)
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - REACT_APP_YOUR_HOSTNAME="http://server:5000"

  server:
    build: ./server
    image: my-server-image
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0

~                                                                                                                               
~                                                                                                                               
~                                                                                                                               
~                                   